config/routes.rb
Rails.application.routes.draw do
  root to: "books#top"
  get "books" => "books#index"
  post "books" => "books#create"
  get "books/:id" => "books#show", as: 'book'
  get "books/:id/edit" => "books#edit", as: "edit_book"
  patch "books/:id" => "books#update", as: "update_book"
  delete "books/:id" => "books#destroy", as: "destroy_book"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, {presence: true}
  validates :body, {presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render "index"
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to "/books"
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class = "edit-body">
<h1>Editing Book</h1>
<br>

<% if @book.errors.any?%>
  <h3>error</h3>
  <% @book.errors.full_messages.each do |m|%>
    <li><%= m %></li>
  <% end %>
<% end %>

<%= form_for(@book, url:book_path(@book.id)) do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>body</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Update Book"%>
  <br>
  <br>
  <%= link_to "show",book_path(@book.id), class:"curd-link"%>
  <%= link_to "back","/books", class:"curd-link"%>
<% end %>
</div>

app/views/books/index.html.erb
<div class="index-body">

  <h1>Books</h1>
  <table border = "0">

    <tr class= table-head>
      <th>title</th>
      <th>body</th>
    </tr>

    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "show", book_path(book.id), class: "curd-link" %></td>
      <td><%= link_to "edit", edit_book_path(book.id), class: "curd-link" %></td>
      <td><%= link_to "destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "are you sure?", class: "curd-link" %></td>
    </tr>
    <% end %>

  </table>
  <br>
  <h1>New book</h1>


  <%= form_for(@book, url: "/books") do |f| %>
  <% if @book.errors.any?%>
    <h3>error</h3>
    <% @book.errors.full_messages.each do |m|%>
      <li><%= m %></li>
    <% end %>
  <% end %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %><br>
    <%= f.submit "Create Book" %>
  <% end %>

</div>

app/views/books/show.html.erb
<div class="show-body">
<span class="headline">title:</span>
<span><%= "#{@book.title}" %></span>
<br>
<span class = "headline">body:</span>
<span><%= "#{@book.body}" %></span>

<br>
<br>
<%= link_to "edit", edit_book_path(@book.id), class:"curd-link" %>
<%= link_to "back", "/books", class:"curd-link" %>
</div>

app/views/books/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有することができます</p>
<br>

<%= link_to "start","/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>